// Command chat is a runnable example: a multi-user chat server built with
// knet's roommanager package.
//
// It demonstrates users joining/leaving a room, broadcasting chat messages,
// presence notifications via a Colyseus-style RoomHandler (see lobbyRoom in
// server.go), and telling voluntary disconnects (user clicked "Leave") apart
// from involuntary ones (network drop / timeout) using the OnDisconnect
// callback's `voluntary bool` argument.
//
// Run:
//
//	go run .
//
// Then open https://localhost:8081 in a browser — see
// docs-site/docs/chat-example.md for the full walkthrough.
//
// The example runs over TLS (wss://), matching how browsers behave in
// production: a page served over plain http:// is allowed to open a plain
// ws:// socket, but a page served over https:// requires wss://. Rather than
// teach a setup that breaks the moment you deploy behind TLS, this example
// uses a self-signed dev certificate from the start — generated by
// `make chat-example` (or manually, see cert.pem/key.pem below).
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/luciancaetano/knet"
	"github.com/luciancaetano/knet/roommanager"
	"github.com/luciancaetano/knet/ws"
)

// certFile and keyFile are a self-signed dev certificate for localhost,
// committed to the repo for convenience — this is a test/example cert with
// no real-world validity, not a production secret. Regenerate them with
// `make chat-example-certs` if they ever expire (365-day validity).
const (
	certFile = "cert.pem"
	keyFile  = "key.pem"
)

// jsClientDist is where the built @lcaetano/knet-client ESM bundle lives —
// index.html imports it from here (/vendor/knet-client.js) instead of a CDN,
// so the example always runs against the client code actually in this repo,
// with no npm publish/CDN propagation delay in the loop. Run `npm run build`
// in clients/js after changing the client.
const jsClientDist = "../../clients/js/dist"

// --8<-- [start:static-server]
// serveStatic serves index.html (and knet-dog.png) over HTTPS on its own
// port, so the example works with a single "go run ." — no separate static
// server needed. The WebSocket traffic still goes to the knet server on
// :8080/ws (also over TLS, i.e. wss://).
func serveStatic(ctx context.Context, addr string) *http.Server {
	mux := http.NewServeMux()
	mux.Handle("/vendor/", http.StripPrefix("/vendor/", http.FileServer(http.Dir(jsClientDist))))
	mux.Handle("/", http.FileServer(http.Dir(".")))

	srv := &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServeTLS(certFile, keyFile); err != nil && err != http.ErrServerClosed {
			log.Printf("static file server error: %v", err)
		}
	}()

	go func() {
		<-ctx.Done()
		stopCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		srv.Shutdown(stopCtx)
	}()

	return srv
}

// --8<-- [end:static-server]

// --8<-- [start:bootstrap]
func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	chat := newChatServer()

	// hooks fans a single onConnect/onDisconnect slot out to multiple
	// independent listeners: our own logging below, and RoomManager's own
	// connect/disconnect tracking (registered by roommanager.New further
	// down) — both run off the same *knet.ConnectHooks.
	hooks := &knet.ConnectHooks{}
	hooks.OnConnect(func(client knet.Client) bool {
		log.Printf("client connected: id=%s addr=%s", client.ID(), client.RemoteAddr())
		return true
	})
	hooks.OnDisconnect(func(client knet.Client, voluntary bool) {
		// roommanager's own listener on this same hook (see below) already
		// decides what happens to room membership from voluntary — a
		// voluntary leave removes it now, an involuntary drop keeps it
		// pending for a grace period so a reconnect can resume it. We only
		// need to clear the name we don't need anymore.
		log.Printf("client disconnected: id=%s addr=%s voluntary=%v", client.ID(), client.RemoteAddr(), voluntary)
		chat.names.delete(client.ID())
	})

	cfg := ws.NewConfig(
		":8080",
		ws.DefaultRateLimitConfig(),
		ws.AllOrigins(),
		hooks.DispatchConnect,
		hooks.DispatchDisconnect,
	)
	cfg = ws.WithTLS(cfg, certFile, keyFile) // enables wss://

	server := ws.New(cfg)

	// roommanager.New needs the *ws.Server to register its handlers on
	// (hence why it's built here, not in newChatServer) and the same hooks
	// above, so it can self-register HandleConnect/HandleDisconnect instead
	// of the app calling them by hand.
	chat.roomManager = roommanager.New(server, hooks, roommanager.Config{})

	// Define registers "lobby" as a room type: the first client to join a
	// room with roomType "lobby" (see index.html's joinRoom call) creates
	// one lobbyRoom instance, which then owns that room's presence
	// broadcasts via its own OnJoin/OnLeave — see server.go.
	chat.roomManager.Define("lobby", func() roommanager.RoomHandler {
		return &lobbyRoom{names: chat.names}
	})

	// OnResume is a single-slot field on ServerConfig (not a ConnectHooks
	// listener): it fires on a reconnect within the grace period, letting a
	// client automatically resume its previous room membership instead of
	// being treated as brand new.
	cfg.OnResume = func(client knet.Client, previousRooms []string) bool {
		return chat.roomManager.HandleResume(client, previousRooms)
	}

	serveStatic(ctx, ":8081")

	log.Println("chat server listening on wss://localhost:8080/ws — open https://localhost:8081 to connect")
	log.Println("self-signed cert: your browser will warn on first visit to both origins — accept it to continue")
	if err := server.Start(ctx); err != nil {
		log.Fatalf("start: %v", err)
	}

	<-ctx.Done()
	log.Println("shutting down...")
}

// --8<-- [end:bootstrap]
