// Command chat is a runnable example: a multi-user chat server built with
// knet's room package.
//
// It demonstrates users joining/leaving, broadcasting chat messages,
// presence notifications, and telling voluntary disconnects (user clicked
// "Leave") apart from involuntary ones (network drop / timeout) using the
// OnDisconnect callback's `voluntary bool` argument.
//
// Run:
//
//	go run .
//
// Then open https://localhost:8081 in a browser — see
// docs-site/docs/chat-example.md for the full walkthrough.
//
// The example runs over TLS (wss://), matching how browsers behave in
// production: a page served over plain http:// is allowed to open a plain
// ws:// socket, but a page served over https:// requires wss://. Rather than
// teach a setup that breaks the moment you deploy behind TLS, this example
// uses a self-signed dev certificate from the start — generated by
// `make chat-example` (or manually, see cert.pem/key.pem below).
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/luciancaetano/knet"
	"github.com/luciancaetano/knet/ws"
)

// certFile and keyFile are a self-signed dev certificate for localhost,
// committed to the repo for convenience — this is a test/example cert with
// no real-world validity, not a production secret. Regenerate them with
// `make chat-example-certs` if they ever expire (365-day validity).
const (
	certFile = "cert.pem"
	keyFile  = "key.pem"
)

// --8<-- [start:static-server]
// serveStatic serves index.html (and knet-dog.png) over HTTPS on its own
// port, so the example works with a single "go run ." — no separate static
// server needed. The WebSocket traffic still goes to the knet server on
// :8080/ws (also over TLS, i.e. wss://).
func serveStatic(ctx context.Context, addr string) *http.Server {
	srv := &http.Server{
		Addr:              addr,
		Handler:           http.FileServer(http.Dir(".")),
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServeTLS(certFile, keyFile); err != nil && err != http.ErrServerClosed {
			log.Printf("static file server error: %v", err)
		}
	}()

	go func() {
		<-ctx.Done()
		stopCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		srv.Shutdown(stopCtx)
	}()

	return srv
}

// --8<-- [end:static-server]

// --8<-- [start:bootstrap]
func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	chat := newChatServer()

	// hooks fans a single onConnect/onDisconnect slot out to multiple
	// independent listeners: chat's own logging and RoomManager's tracking
	// (registered inside attachRoomManager) both run off the same hooks.
	hooks := &knet.ConnectHooks{}
	hooks.OnConnect(chat.onConnect)
	hooks.OnDisconnect(chat.onDisconnect)

	cfg := ws.NewConfig(
		":8080",
		ws.DefaultRateLimitConfig(),
		ws.AllOrigins(),
		hooks.DispatchConnect,
		hooks.DispatchDisconnect,
	)
	cfg = ws.WithTLS(cfg, certFile, keyFile) // enables wss://
	cfg.OnResume = chat.onResume             // resumes pending room membership after a reconnect

	server := ws.New(cfg)
	chat.attachRoomManager(server, hooks)

	if err := server.RegisterHandler(ctx, CmdSetName, chat.handleSetName); err != nil {
		log.Fatalf("register SetName handler: %v", err)
	}

	serveStatic(ctx, ":8081")

	log.Println("chat server listening on wss://localhost:8080/ws — open https://localhost:8081 to connect")
	log.Println("self-signed cert: your browser will warn on first visit to both origins — accept it to continue")
	if err := server.Start(ctx); err != nil {
		log.Fatalf("start: %v", err)
	}

	<-ctx.Done()
	log.Println("shutting down...")
}

// --8<-- [end:bootstrap]
